default_agent: agent_runtime
agents:
  agent_runtime:
    name: agent_runtime
    entrypoint: src/agentcore_runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::434444145045:role/agentcore-strands_agent_role-role
      account: '434444145045'
      region: us-west-2
      ecr_repository: 434444145045.dkr.ecr.us-west-2.amazonaws.com/bedrock_agentcore-agent_runtime
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agent_runtime-VF0RLdG8eG
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:434444145045:runtime/agent_runtime-VF0RLdG8eG
      agent_session_id: null
    authorizer_configuration: null
    oauth_configuration: null
