version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "7002:7002"
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - STRANDS_MODEL_PROVIDER=${STRANDS_MODEL_PROVIDER:-bedrock}
      - API_KEY=${API_KEY:-123456}
      - MAX_TURNS=${MAX_TURNS:-200}
      - INACTIVE_TIME=${INACTIVE_TIME:-1440}
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs
      - ./docs:/app/docs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./react_ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SERVER_MCP_BASE_URL=http://backend:7002
      - NEXT_PUBLIC_MCP_BASE_URL=/api
      - NEXT_PUBLIC_API_KEY=123456
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
